// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: forwardrpc/forward.proto

package forwardrpc

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	metricpb "github.com/stripe/veneur/samplers/metricpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// MetricList just wraps a list of metricpb.Metric's.
type MetricList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*metricpb.Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *MetricList) Reset() {
	*x = MetricList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forwardrpc_forward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricList) ProtoMessage() {}

func (x *MetricList) ProtoReflect() protoreflect.Message {
	mi := &file_forwardrpc_forward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricList.ProtoReflect.Descriptor instead.
func (*MetricList) Descriptor() ([]byte, []int) {
	return file_forwardrpc_forward_proto_rawDescGZIP(), []int{0}
}

func (x *MetricList) GetMetrics() []*metricpb.Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_forwardrpc_forward_proto protoreflect.FileDescriptor

var file_forwardrpc_forward_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x72, 0x70, 0x63, 0x1a, 0x1e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x73,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x70, 0x62, 0x2e, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x32, 0x4a, 0x0a,
	0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x3f, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x16, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x2f, 0x76,
	0x65, 0x6e, 0x65, 0x75, 0x72, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forwardrpc_forward_proto_rawDescOnce sync.Once
	file_forwardrpc_forward_proto_rawDescData = file_forwardrpc_forward_proto_rawDesc
)

func file_forwardrpc_forward_proto_rawDescGZIP() []byte {
	file_forwardrpc_forward_proto_rawDescOnce.Do(func() {
		file_forwardrpc_forward_proto_rawDescData = protoimpl.X.CompressGZIP(file_forwardrpc_forward_proto_rawDescData)
	})
	return file_forwardrpc_forward_proto_rawDescData
}

var file_forwardrpc_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_forwardrpc_forward_proto_goTypes = []interface{}{
	(*MetricList)(nil),      // 0: forwardrpc.MetricList
	(*metricpb.Metric)(nil), // 1: metricpb.Metric
	(*empty.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_forwardrpc_forward_proto_depIdxs = []int32{
	1, // 0: forwardrpc.MetricList.metrics:type_name -> metricpb.Metric
	0, // 1: forwardrpc.Forward.SendMetrics:input_type -> forwardrpc.MetricList
	2, // 2: forwardrpc.Forward.SendMetrics:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forwardrpc_forward_proto_init() }
func file_forwardrpc_forward_proto_init() {
	if File_forwardrpc_forward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forwardrpc_forward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forwardrpc_forward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forwardrpc_forward_proto_goTypes,
		DependencyIndexes: file_forwardrpc_forward_proto_depIdxs,
		MessageInfos:      file_forwardrpc_forward_proto_msgTypes,
	}.Build()
	File_forwardrpc_forward_proto = out.File
	file_forwardrpc_forward_proto_rawDesc = nil
	file_forwardrpc_forward_proto_goTypes = nil
	file_forwardrpc_forward_proto_depIdxs = nil
}
