// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: forwardrpc/forward.proto

package forwardrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	metricpb "github.com/stripe/veneur/v14/samplers/metricpb"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// MetricList just wraps a list of metricpb.Metric's.
type MetricList struct {
	Metrics []*metricpb.Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (m *MetricList) Reset()         { *m = MetricList{} }
func (m *MetricList) String() string { return proto.CompactTextString(m) }
func (*MetricList) ProtoMessage()    {}
func (*MetricList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9bdf2b06f7b9ea, []int{0}
}
func (m *MetricList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetricList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetricList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetricList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricList.Merge(m, src)
}
func (m *MetricList) XXX_Size() int {
	return m.Size()
}
func (m *MetricList) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricList.DiscardUnknown(m)
}

var xxx_messageInfo_MetricList proto.InternalMessageInfo

func (m *MetricList) GetMetrics() []*metricpb.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*MetricList)(nil), "forwardrpc.MetricList")
}

func init() { proto.RegisterFile("forwardrpc/forward.proto", fileDescriptor_0f9bdf2b06f7b9ea) }

var fileDescriptor_0f9bdf2b06f7b9ea = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0xcb, 0x2f, 0x2a,
	0x4f, 0x2c, 0x4a, 0x29, 0x2a, 0x48, 0xd6, 0x87, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xb8, 0x10, 0x32, 0x52, 0x72, 0xc5, 0x89, 0xb9, 0x05, 0x39, 0xa9, 0x45, 0xc5, 0xfa, 0xb9, 0xa9,
	0x25, 0x45, 0x99, 0xc9, 0x05, 0x49, 0x50, 0x06, 0x44, 0xad, 0x94, 0x74, 0x7a, 0x7e, 0x7e, 0x7a,
	0x4e, 0xaa, 0x3e, 0x98, 0x97, 0x54, 0x9a, 0xa6, 0x9f, 0x9a, 0x5b, 0x50, 0x52, 0x09, 0x91, 0x54,
	0xb2, 0xe0, 0xe2, 0xf2, 0x05, 0x2b, 0xf6, 0xc9, 0x2c, 0x2e, 0x11, 0xd2, 0xe2, 0x62, 0x87, 0x68,
	0x2d, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd0, 0x83, 0x99, 0xa9, 0x07, 0x51, 0x16,
	0x04, 0x53, 0x60, 0xd4, 0xc9, 0xc8, 0xc5, 0xee, 0x06, 0x71, 0x85, 0x90, 0x3d, 0x17, 0x77, 0x70,
	0x6a, 0x5e, 0x0a, 0x44, 0x49, 0xb1, 0x90, 0x98, 0x1e, 0xc2, 0x79, 0x7a, 0x08, 0xe3, 0xa5, 0xc4,
	0xf4, 0x20, 0x4e, 0xd1, 0x83, 0x39, 0x45, 0xcf, 0x15, 0xe4, 0x14, 0x25, 0x06, 0x21, 0x5b, 0x2e,
	0x5e, 0x24, 0x03, 0xc2, 0x8c, 0x84, 0x30, 0x2c, 0xc6, 0xad, 0x59, 0x83, 0xd1, 0x49, 0xe2, 0xc4,
	0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1,
	0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0x92, 0xd8, 0xc0, 0xaa, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x72, 0xd7, 0x3e, 0xf8, 0x4b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ForwardClient is the client API for Forward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ForwardClient interface {
	// SendMetrics sends a batch of metrics at once, and returns no response.
	SendMetrics(ctx context.Context, in *MetricList, opts ...grpc.CallOption) (*empty.Empty, error)
	SendMetricsV2(ctx context.Context, opts ...grpc.CallOption) (Forward_SendMetricsV2Client, error)
}

type forwardClient struct {
	cc *grpc.ClientConn
}

func NewForwardClient(cc *grpc.ClientConn) ForwardClient {
	return &forwardClient{cc}
}

func (c *forwardClient) SendMetrics(ctx context.Context, in *MetricList, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/forwardrpc.Forward/SendMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardClient) SendMetricsV2(ctx context.Context, opts ...grpc.CallOption) (Forward_SendMetricsV2Client, error) {
	stream, err := c.cc.NewStream(ctx, &_Forward_serviceDesc.Streams[0], "/forwardrpc.Forward/SendMetricsV2", opts...)
	if err != nil {
		return nil, err
	}
	x := &forwardSendMetricsV2Client{stream}
	return x, nil
}

type Forward_SendMetricsV2Client interface {
	Send(*metricpb.Metric) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type forwardSendMetricsV2Client struct {
	grpc.ClientStream
}

func (x *forwardSendMetricsV2Client) Send(m *metricpb.Metric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *forwardSendMetricsV2Client) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ForwardServer is the server API for Forward service.
type ForwardServer interface {
	// SendMetrics sends a batch of metrics at once, and returns no response.
	SendMetrics(context.Context, *MetricList) (*empty.Empty, error)
	SendMetricsV2(Forward_SendMetricsV2Server) error
}

func RegisterForwardServer(s *grpc.Server, srv ForwardServer) {
	s.RegisterService(&_Forward_serviceDesc, srv)
}

func _Forward_SendMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardServer).SendMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forwardrpc.Forward/SendMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardServer).SendMetrics(ctx, req.(*MetricList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forward_SendMetricsV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ForwardServer).SendMetricsV2(&forwardSendMetricsV2Server{stream})
}

type Forward_SendMetricsV2Server interface {
	SendAndClose(*empty.Empty) error
	Recv() (*metricpb.Metric, error)
	grpc.ServerStream
}

type forwardSendMetricsV2Server struct {
	grpc.ServerStream
}

func (x *forwardSendMetricsV2Server) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *forwardSendMetricsV2Server) Recv() (*metricpb.Metric, error) {
	m := new(metricpb.Metric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Forward_serviceDesc = grpc.ServiceDesc{
	ServiceName: "forwardrpc.Forward",
	HandlerType: (*ForwardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMetrics",
			Handler:    _Forward_SendMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMetricsV2",
			Handler:       _Forward_SendMetricsV2_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "forwardrpc/forward.proto",
}

func (m *MetricList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for _, msg := range m.Metrics {
			dAtA[i] = 0xa
			i++
			i = encodeVarintForward(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintForward(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *MetricList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovForward(uint64(l))
		}
	}
	return n
}

func sovForward(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozForward(x uint64) (n int) {
	return sovForward(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MetricList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowForward
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowForward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthForward
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthForward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, &metricpb.Metric{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipForward(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthForward
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthForward
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipForward(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowForward
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowForward
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowForward
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthForward
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthForward
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowForward
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipForward(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthForward
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthForward = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowForward   = fmt.Errorf("proto: integer overflow")
)
