load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_prefix", "go_test")

go_prefix("github.com/stripe/veneur")

go_library(
    name = "go_default_library",
    srcs = [
        "config.go",
        "config_parse.go",
        "config_proxy.go",
        "consul.go",
        "datadog_trace_span.go",
        "discoverer.go",
        "flusher.go",
        "generate.go",
        "handlers_global.go",
        "http.go",
        "proxy.go",
        "sentry.go",
        "server.go",
        "socket.go",
        "socket_linux.go",
        "worker.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//plugins:go_default_library",
        "//plugins/influxdb:go_default_library",
        "//plugins/localfile:go_default_library",
        "//plugins/s3:go_default_library",
        "//samplers:go_default_library",
        "//ssf:go_default_library",
        "//trace:go_default_library",
        "//vendor:github.com/DataDog/datadog-go/statsd",
        "//vendor:github.com/Sirupsen/logrus",
        "//vendor:github.com/getsentry/raven-go",
        "//vendor:github.com/golang/protobuf/proto",
        "//vendor:github.com/hashicorp/consul/api",
        "//vendor:github.com/pkg/profile",
        "//vendor:github.com/zenazn/goji/bind",
        "//vendor:github.com/zenazn/goji/graceful",
        "//vendor:goji.io",
        "//vendor:goji.io/pat",
        "//vendor:golang.org/x/net/context",
        "//vendor:golang.org/x/sys/unix",
        "//vendor:gopkg.in/yaml.v2",
        "//vendor:stathat.com/c/consistent",
        "@com_github_aws_aws_sdk_go//aws:go_default_library",
        "@com_github_aws_aws_sdk_go//aws/credentials:go_default_library",
        "@com_github_aws_aws_sdk_go//aws/session:go_default_library",
        "@com_github_aws_aws_sdk_go//service/s3:go_default_library",
        "@com_github_aws_aws_sdk_go//service/s3/s3iface:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "config_test.go",
        "consul_discovery_test.go",
        "flusher_test.go",
        "http_test.go",
        "parser_test.go",
        "proxy_test.go",
        "sentry_test.go",
        "server_test.go",
        "socket_test.go",
        "worker_test.go",
    ],
    data = [
        "example.yaml",
        "example_host.yaml",
        "example_proxy.yaml",
        "//fixtures:test_data",
    ],
    library = ":go_default_library",
    deps = [
        "//plugins/s3:go_default_library",
        "//plugins/s3/mock:go_default_library",
        "//samplers:go_default_library",
        "//tdigest:go_default_library",
        "//vendor:github.com/DataDog/datadog-go/statsd",
        "//vendor:github.com/Sirupsen/logrus",
        "//vendor:github.com/getsentry/raven-go",
        "//vendor:github.com/stretchr/testify/assert",
        "@com_github_aws_aws_sdk_go//aws:go_default_library",
        "@com_github_aws_aws_sdk_go//service/s3:go_default_library",
    ],
)
