// Code generated by protoc-gen-go.
// source: sample.proto
// DO NOT EDIT!

/*
Package ssf is a generated protocol buffer package.

It is generated from these files:
	sample.proto

It has these top-level messages:
	SSFTag
	SSFTrace
	SSFSample
*/
package ssf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SSFSample_Metric int32

const (
	SSFSample_COUNTER   SSFSample_Metric = 0
	SSFSample_GAUGE     SSFSample_Metric = 1
	SSFSample_HISTOGRAM SSFSample_Metric = 2
	SSFSample_SET       SSFSample_Metric = 3
	SSFSample_STATUS    SSFSample_Metric = 4
	SSFSample_EVENT     SSFSample_Metric = 5
	SSFSample_TRACE     SSFSample_Metric = 6
)

var SSFSample_Metric_name = map[int32]string{
	0: "COUNTER",
	1: "GAUGE",
	2: "HISTOGRAM",
	3: "SET",
	4: "STATUS",
	5: "EVENT",
	6: "TRACE",
}
var SSFSample_Metric_value = map[string]int32{
	"COUNTER":   0,
	"GAUGE":     1,
	"HISTOGRAM": 2,
	"SET":       3,
	"STATUS":    4,
	"EVENT":     5,
	"TRACE":     6,
}

func (x SSFSample_Metric) String() string {
	return proto.EnumName(SSFSample_Metric_name, int32(x))
}
func (SSFSample_Metric) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type SSFSample_Status int32

const (
	SSFSample_OK       SSFSample_Status = 0
	SSFSample_WARNING  SSFSample_Status = 1
	SSFSample_CRITICAL SSFSample_Status = 2
	SSFSample_UNKNOWN  SSFSample_Status = 3
)

var SSFSample_Status_name = map[int32]string{
	0: "OK",
	1: "WARNING",
	2: "CRITICAL",
	3: "UNKNOWN",
}
var SSFSample_Status_value = map[string]int32{
	"OK":       0,
	"WARNING":  1,
	"CRITICAL": 2,
	"UNKNOWN":  3,
}

func (x SSFSample_Status) String() string {
	return proto.EnumName(SSFSample_Status_name, int32(x))
}
func (SSFSample_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

type SSFTag struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *SSFTag) Reset()                    { *m = SSFTag{} }
func (m *SSFTag) String() string            { return proto.CompactTextString(m) }
func (*SSFTag) ProtoMessage()               {}
func (*SSFTag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SSFTag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SSFTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SSFTrace struct {
	TraceId  int64 `protobuf:"varint,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	Id       int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	ParentId int64 `protobuf:"varint,3,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
}

func (m *SSFTrace) Reset()                    { *m = SSFTrace{} }
func (m *SSFTrace) String() string            { return proto.CompactTextString(m) }
func (*SSFTrace) ProtoMessage()               {}
func (*SSFTrace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SSFTrace) GetTraceId() int64 {
	if m != nil {
		return m.TraceId
	}
	return 0
}

func (m *SSFTrace) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SSFTrace) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type SSFSample struct {
	Metric     SSFSample_Metric `protobuf:"varint,1,opt,name=metric,enum=ssf.SSFSample_Metric" json:"metric,omitempty"`
	Name       string           `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Timestamp  int64            `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Message    string           `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	Status     SSFSample_Status `protobuf:"varint,5,opt,name=status,enum=ssf.SSFSample_Status" json:"status,omitempty"`
	Value      float64          `protobuf:"fixed64,6,opt,name=value" json:"value,omitempty"`
	SampleRate float32          `protobuf:"fixed32,7,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	Tags       []*SSFTag        `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
	Unit       string           `protobuf:"bytes,9,opt,name=unit" json:"unit,omitempty"`
	Trace      *SSFTrace        `protobuf:"bytes,10,opt,name=trace" json:"trace,omitempty"`
}

func (m *SSFSample) Reset()                    { *m = SSFSample{} }
func (m *SSFSample) String() string            { return proto.CompactTextString(m) }
func (*SSFSample) ProtoMessage()               {}
func (*SSFSample) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SSFSample) GetMetric() SSFSample_Metric {
	if m != nil {
		return m.Metric
	}
	return SSFSample_COUNTER
}

func (m *SSFSample) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SSFSample) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SSFSample) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SSFSample) GetStatus() SSFSample_Status {
	if m != nil {
		return m.Status
	}
	return SSFSample_OK
}

func (m *SSFSample) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SSFSample) GetSampleRate() float32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *SSFSample) GetTags() []*SSFTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SSFSample) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *SSFSample) GetTrace() *SSFTrace {
	if m != nil {
		return m.Trace
	}
	return nil
}

func init() {
	proto.RegisterType((*SSFTag)(nil), "ssf.SSFTag")
	proto.RegisterType((*SSFTrace)(nil), "ssf.SSFTrace")
	proto.RegisterType((*SSFSample)(nil), "ssf.SSFSample")
	proto.RegisterEnum("ssf.SSFSample_Metric", SSFSample_Metric_name, SSFSample_Metric_value)
	proto.RegisterEnum("ssf.SSFSample_Status", SSFSample_Status_name, SSFSample_Status_value)
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x6b, 0xdb, 0x30,
	0x14, 0xae, 0xed, 0xf8, 0xd7, 0x73, 0x5b, 0xc4, 0x63, 0x03, 0x8d, 0x0d, 0x66, 0xbc, 0x8b, 0x2f,
	0xcb, 0x21, 0xbb, 0xec, 0x6a, 0x82, 0x9b, 0x99, 0xae, 0x0e, 0x48, 0xca, 0x0a, 0xbb, 0x14, 0xad,
	0x56, 0x83, 0xa1, 0x4e, 0x83, 0xa5, 0xec, 0xaf, 0xdd, 0x1f, 0x33, 0x24, 0xa7, 0xc9, 0x0e, 0xbb,
	0x3d, 0x7d, 0x3f, 0xfc, 0xbd, 0xf7, 0x61, 0xb8, 0xd4, 0x72, 0xd8, 0x3f, 0xab, 0xf9, 0x7e, 0x7c,
	0x31, 0x2f, 0x18, 0x68, 0xfd, 0x54, 0x2c, 0x20, 0xe2, 0xfc, 0x46, 0xc8, 0x2d, 0x22, 0xcc, 0x76,
	0x72, 0x50, 0xd4, 0xcb, 0xbd, 0x32, 0x65, 0x6e, 0xc6, 0x37, 0x10, 0xfe, 0x96, 0xcf, 0x07, 0x45,
	0x7d, 0x07, 0x4e, 0x8f, 0x82, 0x41, 0x62, 0x3d, 0xa3, 0x7c, 0x54, 0xf8, 0x0e, 0x12, 0x63, 0x87,
	0x87, 0xbe, 0x73, 0xce, 0x80, 0xc5, 0xee, 0xdd, 0x74, 0x78, 0x0d, 0x7e, 0xdf, 0x39, 0x67, 0xc0,
	0xfc, 0xbe, 0xc3, 0xf7, 0x90, 0xee, 0xe5, 0xa8, 0x76, 0xc6, 0x6a, 0x03, 0x07, 0x27, 0x13, 0xd0,
	0x74, 0xc5, 0x9f, 0x00, 0x52, 0xce, 0x6f, 0xb8, 0x5b, 0x10, 0x3f, 0x43, 0x34, 0x28, 0x33, 0xf6,
	0x8f, 0xee, 0x9b, 0xd7, 0x8b, 0xb7, 0x73, 0xad, 0x9f, 0xe6, 0x27, 0x7e, 0x7e, 0xe7, 0x48, 0x76,
	0x14, 0x9d, 0x56, 0xf7, 0xff, 0x59, 0xfd, 0x03, 0xa4, 0xa6, 0x1f, 0x94, 0x36, 0x72, 0xd8, 0x1f,
	0xd3, 0xce, 0x00, 0x52, 0x88, 0x07, 0xa5, 0xb5, 0xdc, 0x2a, 0x3a, 0x73, 0xa6, 0xd7, 0xa7, 0x8d,
	0xd6, 0x46, 0x9a, 0x83, 0xa6, 0xe1, 0x7f, 0xa3, 0xb9, 0x23, 0xd9, 0x51, 0x74, 0x6e, 0x28, 0xca,
	0xbd, 0xd2, 0x3b, 0x36, 0x84, 0x1f, 0x21, 0x9b, 0xaa, 0x7e, 0x18, 0xa5, 0x51, 0x34, 0xce, 0xbd,
	0xd2, 0x67, 0x30, 0x41, 0x4c, 0x1a, 0x2b, 0x98, 0x19, 0xb9, 0xd5, 0x34, 0xc9, 0x83, 0x32, 0x5b,
	0x64, 0xaf, 0x19, 0x42, 0x6e, 0x99, 0x23, 0xec, 0x49, 0x87, 0x5d, 0x6f, 0x68, 0x3a, 0x9d, 0x64,
	0x67, 0xfc, 0x04, 0xa1, 0xeb, 0x96, 0x42, 0xee, 0x95, 0xd9, 0xe2, 0xea, 0xe4, 0xb2, 0x20, 0x9b,
	0xb8, 0xe2, 0x27, 0x44, 0x53, 0x3b, 0x98, 0x41, 0xbc, 0x5c, 0x6f, 0x5a, 0x51, 0x33, 0x72, 0x81,
	0x29, 0x84, 0xab, 0x6a, 0xb3, 0xaa, 0x89, 0x87, 0x57, 0x90, 0x7e, 0x6b, 0xb8, 0x58, 0xaf, 0x58,
	0x75, 0x47, 0x7c, 0x8c, 0x21, 0xe0, 0xb5, 0x20, 0x01, 0x02, 0x44, 0x5c, 0x54, 0x62, 0xc3, 0xc9,
	0xcc, 0xca, 0xeb, 0x1f, 0x75, 0x2b, 0x48, 0x68, 0x47, 0xc1, 0xaa, 0x65, 0x4d, 0xa2, 0xe2, 0x2b,
	0x44, 0xd3, 0xf9, 0x18, 0x81, 0xbf, 0xbe, 0x25, 0x17, 0x36, 0xe3, 0xbe, 0x62, 0x6d, 0xd3, 0xae,
	0x88, 0x87, 0x97, 0x90, 0x2c, 0x59, 0x23, 0x9a, 0x65, 0xf5, 0x9d, 0xf8, 0x96, 0xda, 0xb4, 0xb7,
	0xed, 0xfa, 0xbe, 0x25, 0xc1, 0xaf, 0xc8, 0xfd, 0x72, 0x5f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x1a, 0x05, 0x61, 0x43, 0x82, 0x02, 0x00, 0x00,
}
