// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tdigest/tdigest.proto

package tdigest

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// MergingDigestData contains all fields necessary to generate a MergingDigest.
// This type should generally just be used when serializing MergingDigest's,
// and doesn't have much of a purpose on its own.
type MergingDigestData struct {
	// Use values rather than pointers for the Centroid array.  This avoids
	// a ton of code changes and probably a lot of allocations as well.
	MainCentroids []Centroid `protobuf:"bytes,1,rep,name=main_centroids,json=mainCentroids,proto3" json:"main_centroids"`
	Compression   float64    `protobuf:"fixed64,2,opt,name=compression,proto3" json:"compression,omitempty"`
	Min           float64    `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64    `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	ReciprocalSum float64    `protobuf:"fixed64,5,opt,name=reciprocalSum,proto3" json:"reciprocalSum,omitempty"`
}

func (m *MergingDigestData) Reset()         { *m = MergingDigestData{} }
func (m *MergingDigestData) String() string { return proto.CompactTextString(m) }
func (*MergingDigestData) ProtoMessage()    {}
func (*MergingDigestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2bb08a1d010917, []int{0}
}
func (m *MergingDigestData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MergingDigestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MergingDigestData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MergingDigestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergingDigestData.Merge(m, src)
}
func (m *MergingDigestData) XXX_Size() int {
	return m.Size()
}
func (m *MergingDigestData) XXX_DiscardUnknown() {
	xxx_messageInfo_MergingDigestData.DiscardUnknown(m)
}

var xxx_messageInfo_MergingDigestData proto.InternalMessageInfo

func (m *MergingDigestData) GetMainCentroids() []Centroid {
	if m != nil {
		return m.MainCentroids
	}
	return nil
}

func (m *MergingDigestData) GetCompression() float64 {
	if m != nil {
		return m.Compression
	}
	return 0
}

func (m *MergingDigestData) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *MergingDigestData) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MergingDigestData) GetReciprocalSum() float64 {
	if m != nil {
		return m.ReciprocalSum
	}
	return 0
}

type Centroid struct {
	Mean    float64   `protobuf:"fixed64,1,opt,name=mean,proto3" json:"mean,omitempty"`
	Weight  float64   `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Samples []float64 `protobuf:"fixed64,3,rep,packed,name=samples,proto3" json:"samples,omitempty"`
}

func (m *Centroid) Reset()         { *m = Centroid{} }
func (m *Centroid) String() string { return proto.CompactTextString(m) }
func (*Centroid) ProtoMessage()    {}
func (*Centroid) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2bb08a1d010917, []int{1}
}
func (m *Centroid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Centroid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Centroid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Centroid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Centroid.Merge(m, src)
}
func (m *Centroid) XXX_Size() int {
	return m.Size()
}
func (m *Centroid) XXX_DiscardUnknown() {
	xxx_messageInfo_Centroid.DiscardUnknown(m)
}

var xxx_messageInfo_Centroid proto.InternalMessageInfo

func (m *Centroid) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Centroid) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Centroid) GetSamples() []float64 {
	if m != nil {
		return m.Samples
	}
	return nil
}

func init() {
	proto.RegisterType((*MergingDigestData)(nil), "tdigest.MergingDigestData")
	proto.RegisterType((*Centroid)(nil), "tdigest.Centroid")
}

func init() { proto.RegisterFile("tdigest/tdigest.proto", fileDescriptor_ea2bb08a1d010917) }

var fileDescriptor_ea2bb08a1d010917 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0x1b, 0x5b, 0x37, 0xc9, 0x98, 0xb8, 0x80, 0x12, 0x3c, 0xc4, 0x32, 0x3c, 0xf4, 0x62,
	0x0b, 0x7a, 0xf7, 0x30, 0x77, 0x15, 0xa4, 0x3e, 0x80, 0xa4, 0x5d, 0xcc, 0x02, 0x4b, 0x52, 0x92,
	0x14, 0xf7, 0x18, 0xbe, 0x91, 0xd7, 0x1d, 0x77, 0xf4, 0x24, 0xd2, 0xbe, 0x88, 0x2c, 0xa6, 0xa0,
	0xa7, 0xfe, 0x7f, 0xbf, 0xff, 0xd7, 0x7c, 0x21, 0xf0, 0xdc, 0xad, 0x04, 0x67, 0xd6, 0x15, 0xe1,
	0x9b, 0x37, 0x46, 0x3b, 0x8d, 0xc6, 0x01, 0x2f, 0x6f, 0xb8, 0x70, 0xeb, 0xb6, 0xca, 0x6b, 0x2d,
	0x0b, 0xae, 0xb9, 0x2e, 0x7c, 0x5f, 0xb5, 0xaf, 0x9e, 0x3c, 0xf8, 0xf4, 0xfb, 0xdf, 0xfc, 0x03,
	0xc0, 0xd9, 0x23, 0x33, 0x5c, 0x28, 0xbe, 0xf4, 0x07, 0x2c, 0xa9, 0xa3, 0xe8, 0x1e, 0x9e, 0x4a,
	0x2a, 0xd4, 0x4b, 0xcd, 0x94, 0x33, 0x5a, 0xac, 0x2c, 0x06, 0x69, 0x9c, 0x4d, 0x6e, 0x67, 0xf9,
	0xb0, 0xf5, 0x21, 0x34, 0x8b, 0x64, 0xf7, 0x75, 0x15, 0x95, 0xd3, 0xc3, 0xf8, 0xe0, 0x2c, 0x4a,
	0xe1, 0xa4, 0xd6, 0xb2, 0x31, 0xcc, 0x5a, 0xa1, 0x15, 0x3e, 0x4a, 0x41, 0x06, 0xca, 0xbf, 0x0a,
	0x9d, 0xc1, 0x58, 0x0a, 0x85, 0x63, 0xdf, 0x1c, 0xa2, 0x37, 0x74, 0x8b, 0x93, 0x60, 0xe8, 0x16,
	0x5d, 0xc3, 0xa9, 0x61, 0xb5, 0x68, 0x8c, 0xae, 0xe9, 0xe6, 0xb9, 0x95, 0xf8, 0xd8, 0x77, 0xff,
	0xe5, 0xfc, 0x09, 0x9e, 0x0c, 0x8b, 0x11, 0x82, 0x89, 0x64, 0x54, 0x61, 0xe0, 0x07, 0x7d, 0x46,
	0x17, 0x70, 0xf4, 0xc6, 0x04, 0x5f, 0xbb, 0x70, 0x8d, 0x40, 0x08, 0xc3, 0xb1, 0xa5, 0xb2, 0xd9,
	0x30, 0x8b, 0xe3, 0x34, 0xce, 0x40, 0x39, 0xe0, 0x02, 0xef, 0x3a, 0x02, 0xf6, 0x1d, 0x01, 0xdf,
	0x1d, 0x01, 0xef, 0x3d, 0x89, 0xf6, 0x3d, 0x89, 0x3e, 0x7b, 0x12, 0x55, 0x23, 0xff, 0x68, 0x77,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x9d, 0x88, 0x88, 0x85, 0x01, 0x00, 0x00,
}

func (m *MergingDigestData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MergingDigestData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.MainCentroids) > 0 {
		for _, msg := range m.MainCentroids {
			dAtA[i] = 0xa
			i++
			i = encodeVarintTdigest(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Compression != 0 {
		dAtA[i] = 0x11
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Compression))))
		i += 8
	}
	if m.Min != 0 {
		dAtA[i] = 0x19
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Min))))
		i += 8
	}
	if m.Max != 0 {
		dAtA[i] = 0x21
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Max))))
		i += 8
	}
	if m.ReciprocalSum != 0 {
		dAtA[i] = 0x29
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.ReciprocalSum))))
		i += 8
	}
	return i, nil
}

func (m *Centroid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Centroid) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Mean != 0 {
		dAtA[i] = 0x9
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Mean))))
		i += 8
	}
	if m.Weight != 0 {
		dAtA[i] = 0x11
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Weight))))
		i += 8
	}
	if len(m.Samples) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTdigest(dAtA, i, uint64(len(m.Samples)*8))
		for _, num := range m.Samples {
			f1 := math.Float64bits(float64(num))
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(f1))
			i += 8
		}
	}
	return i, nil
}

func encodeVarintTdigest(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *MergingDigestData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MainCentroids) > 0 {
		for _, e := range m.MainCentroids {
			l = e.Size()
			n += 1 + l + sovTdigest(uint64(l))
		}
	}
	if m.Compression != 0 {
		n += 9
	}
	if m.Min != 0 {
		n += 9
	}
	if m.Max != 0 {
		n += 9
	}
	if m.ReciprocalSum != 0 {
		n += 9
	}
	return n
}

func (m *Centroid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Mean != 0 {
		n += 9
	}
	if m.Weight != 0 {
		n += 9
	}
	if len(m.Samples) > 0 {
		n += 1 + sovTdigest(uint64(len(m.Samples)*8)) + len(m.Samples)*8
	}
	return n
}

func sovTdigest(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTdigest(x uint64) (n int) {
	return sovTdigest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MergingDigestData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTdigest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MergingDigestData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MergingDigestData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainCentroids", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTdigest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTdigest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTdigest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MainCentroids = append(m.MainCentroids, Centroid{})
			if err := m.MainCentroids[len(m.MainCentroids)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Compression", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Compression = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Min", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Min = float64(math.Float64frombits(v))
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Max", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Max = float64(math.Float64frombits(v))
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReciprocalSum", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.ReciprocalSum = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipTdigest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTdigest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTdigest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Centroid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTdigest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Centroid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Centroid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mean", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Mean = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Weight = float64(math.Float64frombits(v))
		case 3:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
				iNdEx += 8
				v2 := float64(math.Float64frombits(v))
				m.Samples = append(m.Samples, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTdigest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTdigest
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTdigest
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 8
				if elementCount != 0 && len(m.Samples) == 0 {
					m.Samples = make([]float64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					v2 := float64(math.Float64frombits(v))
					m.Samples = append(m.Samples, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Samples", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTdigest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTdigest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTdigest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTdigest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTdigest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTdigest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTdigest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTdigest
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthTdigest
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTdigest
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTdigest(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthTdigest
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTdigest = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTdigest   = fmt.Errorf("proto: integer overflow")
)
