---
# A minimal config file for running veneur in development. Note that
# this won't submit aggregated metrics or spans anywhere - for that,
# you'll need upstream sink config.
stats_address: 127.0.0.1:8200
ssf_listen_addresses:
  - unix:///tmp/veneur.sock
  - udp://127.0.0.1:8128
statsd_listen_addresses:
  - udp://127.0.0.1:8200
trace_max_length_bytes: 16000
num_workers: 4
num_readers: 1
interval: 10s
percentiles:
  - 0.50
  - 0.90

debug: true
debug_ingested_spans: true
debug_flushed_metrics: true
